git:
  depth: 1
language: node_js
node_js:
  - 'node'
script:
  - npm test
  - grep --only-matching --perl-regexp "https?://.+?(?=[\)\"])" README.md | sort --unique | xargs --verbose --max-args 1 curl --output /dev/null --silent --fail --show-error --compressed --retry 3 --retry-delay 2
